dist: bionic
language: php
php:
- '7.3'
- '7.4'
install:
- composer install
script:
- "./vendor/bin/phpunit  --bootstrap ./vendor/autoload.php ./test/ --testdox"
notifications:
  slack:
    secure: HE1QBrshJ0A/KVDPO09w9zyLcYBuRfwpTUIfIb6yZUfe0bKQGTMjZ1/uadnXJXN5P7twPMMZTd5V5/u4Q7Ml59+c7WMppvL467IIePiHrD8UGd2pDVKKFJFjDyEQTRPpPrnk9k485wR/i6BQSIByJk19Leo60gsc2J8xR0XrlBGoMfZb6Obaa/Pn0ACzP3wvb6d4Hab1oCtWw0g+Juzpkj1AV/2f3u1dD1bhS34ayuQDxy7P5Jc3zax3Coc9G0YTcje7RDQoy/Cfv39XrZjs+hdeDpNDUXk/YRMTyHWFaYCKq9QucwkU0Af8gTSDNDjdSLWGHpG4ytFU0k0JnSbPOekaazp0othlA5HQs2FMrgWWZKfVnHcaNwIPuOcWHWln3UisZPss51nsON3xSOhF2bSILASvwsVz+6yygaHAUkoSJzCne6zVQ0M7/KxTZyTEk46ur1pcNIwwyn/hEEArytN+mmARC/QtxIO0p6TFRdct8OBqqXzmkLm70zROIGNDmS3NcU4yO88RSKcYc80X8MNMYb7N/S0k8K0ul4is1cDfAM+/U6RYAfMxgBtp/ZZMblC6PlfIOy8GHtQKjqpztjkMsieOBBIuN/qH1Fs/foWKPKttQtY0ot0q5g91rGE9vq3vx7DlyS71itfZRHz/mYJhnbaG3jZmEXrk/2zdyXo=
